name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: test
    steps:
    # Checks-out the repository under $GITHUB_WORKSPACE, so the build job can access it
    - uses: actions/checkout@v2
    - name: Setup Python package
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install -r requirements.txt
        wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome-stable_current_amd64.deb
        wget -q https://chromedriver.storage.googleapis.com/84.0.4147.30/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        gunicorn app:app &
        sleep 3
        pytest
